[package]
name = "vigil"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "vigil"
path = "src/main.rs"
